[RedirectOutput] Add missing self into flush and implement isatty function
THX to (Dima73) and PLi
____________________

Without self any call to flush will miserably fail with the following error:
TypeError: flush() takes no arguments (1 given)

Also any call to isatty fails too with the following error:
AttributeError: EnigmaOutput instance has no attribute 'isatty'

Hardcode it to True since stderr and stdout have isatty by default True.

>>> import sys
>>> sys.stderr.isatty()
True
>>> sys.stdout.isatty()
True